# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"
mac: "new_mac"
agent: "new"

buffer_size: 5000
batch_size: 16

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "new_learner"
double_q: True
mixing_embed_dim: 32
hypernet_embed: 64

state_shape: 32
latent_action_shape: 12

name: "new"
t_max: 50000
save_model_interval: 10000